version: "3.8"

services:
    composer:
        build: ./.docker/composer
        container_name: composer
        environment:
            - COMPOSER_CACHE_DIR=/composer/.cache/composer
        volumes:
            - ./src:/app
            - ./.docker/composer:/composer
        restart: "no"
        command: ['composer', 'update']

    bower:
        build: ./.docker/bower
        container_name: bower
        volumes:
            - ./src:/data
        restart: "no"
        working_dir: /data
        command: ['bower', 'install', '--allow-root']

    site:
        build: ./.docker/nginx
        container_name: nginx
        volumes:
            - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./src:/var/www/html"
        ports:
            - "8000:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        networks:
            - frontend

    php:
        build: ./.docker/php
        container_name: php
        env_file:
            - ".env"
        volumes:
            - "./.docker/php/config.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini"
            - "./src:/var/www/html"
        restart: always
        networks:
            - frontend
            - backend

    mysql:
        build: ./.docker/mysql
        container_name: mysql
        env_file:
            - ".env"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./src/docs/database.sql:/docker-entrypoint-initdb.d/database.sql
            - db-data:/var/lib/mysql
        restart: always
        networks:
            - backend

volumes:
    db-data:

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge